# Site settings
title: Jake Something
description: 'Business Card Page'
url: 'http://jakesomething.github.io'
baseurl: ''
profilepic: '/images/jake.JPG'
bkimage: '/images/kentucky.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Thomas Zühlke'
  email: jakesomething@hotmail.com
  twitter_username: jakesomething
#  facebook_username: joshgerdes
  github_username:  jakesomething
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
